name: Update News

on:
  schedule:
    # 5分おきに設定（ただしGitHubの混雑状況により遅延します）
    - cron: '*/5 * * * *'
  # これを追加することで、ブラウザのボタン（外部）からの起動を許可します
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # ファイルの書き込み権限を許可

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run Python script
        env:
          # GitHub Secretsに登録したトークンをPythonプログラムに渡します
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: python SHIN_chuspo.py

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          # index.html, stock.json, history.txt の変更をすべて保存
          git add index.html CHUSPO_history.txt CHUSPO_stock.json
          git commit -m "Update news and stock" || echo "No changes to commit"
          git push
